name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag crbm/biosimulations_copasi_api:latest .
    - name: Test the docker image
      env:
        JOB_ID: ${{secrets.JOB_ID}}
        SIMULATION_ID: ${{secrets.SIMULATION_ID}}
        AUTH0_CLIENT_ID: ${{secrets.AUTH0_CLIENT_ID}}
        AUTH0_CLIENT_SECRET: ${{secrets.AUTH0_CLIENT_SECRET}}
        AUTH0_BIOSIMULATIONS_AUDIENCE: ${{secrets.AUTH0_BIOSIMULATIONS_AUDIENCE}}
        AUTH0_TOKEN_URL: ${{secrets.AUTH0_TOKEN_URL}}
        AUTH0_GRANT_TYPE: ${{secrets.AUTH0_GRANT_TYPE}}
        JOBHOOK_URL: ${{secrets.JOBHOOK_URL}}
      run: docker run -v /home/runner/work/CRBM-COPASI/CRBM-COPASI/sample_model/:/usr/local/app/copasi/simulation -e JOB_ID -e SIMULATION_ID -e AUTH0_CLIENT_ID -e AUTH0_CLIENT_SECRET -e AUTH0_BIOSIMULATIONS_AUDIENCE -e AUTH0_TOKEN_URL -e AUTH0_GRANT_TYPE -e JOBHOOK_URL crbm/biosimulations_copasi_api:latest
